//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricStoreMetro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int CatID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> Saleprice { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<decimal> UsedQty { get; set; }
        public Nullable<decimal> RemQty { get; set; }
        public Nullable<int> MeasurementID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
